import Configstore from 'configstore';

export const configstore = new Configstore('muzovano');

export default {
  CANVAS_TOP_PADDING: 6,
  CANVAS_BOTTOM_PADDING: 4,
  CANVAS_FRAME_STROKE_WIDTH: 0.5,
  CANVAS_BG: '#ffffff',
  CANVAS_SIZE: 1000,
  COVER_SIZE: 1000 / 600,
  SHADOW_SIZE: 1.5,
  FONT_PATH_1: 'fonts/NeutralFace.ttf',
  FONT_FAMILY_1: 'Neutral Face',
  FONT_WEIGHT_1: '400',
  FONT_PATH_2: 'fonts/NeutralFace-Bold.ttf',
  FONT_FAMILY_2: 'Neutral Face',
  FONT_WEIGHT_2: '700',
  PREVIEW_FOLDER_PATH: 'preview',
  SPOTIFY_FOLDER_PATH: 'spotifyData',
  VIBRANT_ORDER: [
    'Vibrant',
    'DarkVibrant',
    'LightVibrant',
    'Muted',
    'DarkMuted',
    'LightMuted',
  ],
  DEFAULT_COLOR_ACCENT: 1,
  DEFAULT_COLOR_SECONDARY: 5,
  DEFAULT_COLOR_START: 1,
  DEFAULT_COLOR_END: 5,
  BLUR_RADIUS: 3,
  GRADIENT_DEFAULT_START: 1,
  GRADIENT_DEFAULT_END: 5,
  COLORS: [
    'accent',
    'secondary',
    'start',
    'end',
    'text',
    'logo',
    'frame',
    'vignette',
    'shadow',
  ],
};
